config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :skip => [:registrations], :controllers =>
    {
      sessions: "users/sessions",
      omniauth_callbacks: "users/omniauth_callbacks"
    }

  namespace :admin do
    if Rails.env.development?
      get 'mailer/:action' => 'mailer#:action'
    end
  end

  authenticate :user do
    get 'observe' => 'landing#observe'
    get 'scheme' => 'scheme#index'
    namespace :api do
      resources :schemes, only: [:create, :show, :update, :index]
      resources :observation_sessions, only: [:create, :show, :index] do
        resource :exports, only: [:create]
      end
      resources :observations, only: [:create, :update]
    end
  end

  root 'landing#index'
end

app/models/behavior.rb
class Behavior < ActiveRecord::Base
  self.inheritance_column = '__unused'

  belongs_to :scheme

  alias_attribute :uuid, :id
end

app/models/observation.rb
class Observation < ActiveRecord::Base
  belongs_to :observation_session
  belongs_to :actor, class_name: Subject
  belongs_to :receiver, class_name: Subject
  belongs_to :behavior

  validates_presence_of :observation_session
end

app/models/observation_session.rb
class ObservationSession < ActiveRecord::Base
  belongs_to :scheme
  belongs_to :user

  has_many :observations

  accepts_nested_attributes_for :observations
end

app/models/scheme.rb
class Scheme < ActiveRecord::Base
  has_many :behaviors
  has_many :subjects
  belongs_to :user

  accepts_nested_attributes_for :behaviors
  accepts_nested_attributes_for :subjects

  alias_attribute :uuid, :id

  def self.build_with_associations(new_attributes, new_associations:)
    scheme = new(new_attributes)

    new_associations.each do |name, values|
      values.each { |v| scheme.association(name).build(v) }
    end

    scheme
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :scheme

  alias_attribute :uuid, :id
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :omniauthable,
         :rememberable, :trackable, :validatable

  has_and_belongs_to_many :oauth_credentials
  has_many :schemes
  has_many :observation_sessions

  def self.find_for_google_oauth2(access_token, _signed_in_resource=nil)
    email = access_token.info["email"]
    user = User.where(provider: access_token.provider,
                      uid: access_token.uid).first
    return user if user

    registered_user = User.find_by(email: email)
    registered_user || User.create(provider: access_token.provider,
                                   email: email,
                                   uid: access_token.uid,
                                   password: Devise.friendly_token[0, 20]
                                  )
  end
end

app/controllers/admin/mailer_controller.rb
class Admin::MailerController < ApplicationController
  # This controller is simply a development tool to preview email templates
  def preview_export_email
    @email = User.first.email
    render :file => "export_mailer/export_email.html.erb", :layout => false
  end
end

app/controllers/api/exports_controller.rb
module Api
  class ExportsController < ApplicationController
    def create
      csv_data = ObservationExporter.generate_observation_csv(observation_session)
      email = params[:email_address] || current_user.email

      ExportMailer.export_email(email, params[:subject], csv_data)
      redirect_to root_path
    rescue Mailgun::Error
      head 422
    end

    private

    def observation_session
      ObservationSession.find(params[:observation_session_id])
    end
  end
end

app/controllers/api/observation_sessions_controller.rb
module Api
  class ObservationSessionsController < ApplicationController
    def create
      @observation_session = ObservationSession.find_or_initialize_by(id: id_or_nil)
      @observation_session.assign_attributes(create_params)

      if @observation_session.save
        head 201
      else
        head 422
      end
    end

    def show
      @observation_session = ObservationSession.find(observation_session_id)
    end

    def index
    end

    private

    def id_or_nil
      params.permit(:id)[:id]
    end

    def observation_session_id
      params.require(:id)
    end

    def create_params
      filtered_create_params.merge(metadata: extracted_metadata, user_id: current_user.id)
    end

    def filtered_create_params
      params
        .require(:observation_session)
        .permit(:id, :name, :observation_method,
                :session_interval_seconds, :session_duration_seconds,
                :started_at, :focal_animal_id, :focal_behavior_id,
                :scheme_id, :notes, :metadata,
                observations_attributes: [
                  :started_at, :event_type, :duration_seconds,
                  :time_lag_seconds, :notes,
                  :behavior_id, :actor_id, :receiver_id, :id,
                  modifiers: []
                ]
               )
    end

    def extracted_metadata
      params.dig(:observation_session, :metadata)
    end
  end
end

app/controllers/api/observations_controller.rb
module Api
  class ObservationsController < ApplicationController
    def create
      observation = Observation.create(create_params)

      if observation
        head 201
      else
        head 422
      end
    end

    def update
      observation = Observation.find(observation_id)

      if observation.update_attributes(update_params)
        head 200
      else
        head 422
      end
    end

    private

    def observation_id
      params.require(:id)
    end

    def update_params
      params.require(:observation).permit(:notes)
    end

    def create_params
      params
        .require(:observation)
        .permit(:started_at, :event_type, :duration_seconds,
                :time_lag_seconds, :notes, :observation_session_id,
                :behavior_id, :actor_id, :receiver_id, :id,
                modifiers: [])
    end
  end
end

app/controllers/api/schemes_controller.rb
module Api
  class SchemesController < ApplicationController
    before_action :load_scheme, only: [:show, :update]

    def create
      @scheme = Scheme.build_with_associations(
                            scheme_params.merge(user_id: current_user.id),
                            new_associations: {
                              subjects: subject_params,
                              behaviors: behaviors_params })

      if @scheme.save
        head 201
      else
        head 422
      end
    end

    def show
    end

    def index
      @schemes = Scheme.all
    end

    private

    def scheme_id
      params.require(:id)
    end

    def load_scheme
      @scheme = Scheme.find scheme_id
    end

    def scheme_params
      params.require(:scheme).permit(:id, :name)
    end

    def subject_params
      params
        .require(:scheme)
        .permit(:subjects_attributes => [:id, :name, groups: []])[:subjects_attributes]
    end

    def behaviors_params
      params.require(:scheme).permit(:behaviors_attributes => [:id, :name, :type, :target_type, :mutually_exclusive, :parent_behavior_id])[:behaviors_attributes]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user! unless Rails.env == "development"
  force_ssl if: :ssl_configured?

  def ssl_configured?
    !!Rails.env.production?
  end

  def user_name
    current_user.email.presence || 'Logged in'
  end
  helper_method :user_name
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
end

app/controllers/scheme_controller.rb
class SchemeController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"],
                                        current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success",
                              kind: "Google"
      sign_in_and_redirect @user, event: :authentication
    else
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    if Rails.env.development?
      email = params[:email]
      user = User.find_or_initialize_by(email: email)
      user.save(validate: false)
      sign_in user
      redirect_to root_path
    else
      super
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scheme_helper.rb
module SchemeHelper
end

app/views/landing/index.html.erb
<h2>Animal Observation App</h2>
<h3>Hello Ruby for Good!</h3>
<p>
  <p>
    <%= link_to scheme_path do %>
      <button type="button">My Schemes</button>
    <% end %>
  </p>

  <p>
    <%= link_to observe_path do %>
      <button type="button">My Observations</button>
    <% end %>
  </p>

  <% if current_user.present? && current_user.observation_sessions.count > 0 %>
    <p>
      <%= form_tag api_observation_session_exports_path(current_user.observation_sessions.last) do %>
        <%= hidden_field_tag "email_address", current_user.email %>
        <%= hidden_field_tag "subject", "Animal Observation Session: #{current_user.observation_sessions.last.name}" %>
        <%= submit_tag "Email me my latest observation" %>
      <% end %>
    </p>
  <% end %>
</p>

app/views/landing/observe.html.erb
<div data-mithril-component='ObservationForm'></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="in-process">
<head>
  <meta name="google-site-verification" content="OPS4s1bOQYqea_ni5gN_IRvhwok0xYuYOTZ9-4NpfK4" />
  <title>PandaApp</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
<%- unless flash.keys.empty? %>
<div class="flashes">
  <%- flash.keys.each do |key| -%>
    <p class="flash flash-<%= key %>"><%= self.public_send(key) %></p>
  <%- end -%>
</div>
<%- end -%>

<div class="auth">
<% if user_signed_in? %>
  <p class="auth-as"><%= user_name %></p>
  <%= form_tag(destroy_user_session_path, method: :delete, class: 'auth-end') do %>
    <%= submit_tag('Sign out') %>
  <% end %>
<% else %>
  <p class="auth-entry">
    <%= link_to "Sign in &rarr;".html_safe, new_user_session_path %>
  </p>
<% end %>
</div>

<%= yield %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/scheme/index.html.erb
<div data-mithril-component='SchemeList'></div>

app/views/users/shared/_links.html.erb
<%- if devise_mapping.omniauthable? %>
  <div class="box">
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with your #{OmniAuth::Utils.camelize(provider).sub('Oauth2','')} account",
      omniauth_authorize_path(resource_name, provider),
      class: 'button button-add' %><br />
  <% end -%>
</div>
<% end -%>